### ISSUE TITLE
"Today" is not automatically updated

### ISSUE THREAD

**Issue by bnjbvr** [cozy/cozy-calendar#100]
I have pinned the cozy calendar yesterday (i.e. on the 14th) in a tab. Yesterday, the highlighted box in the calendar (corresponding to the "today" date) was the 14th. Today (i.e. the 15th), the highlighted box is still the 14th (I didn't close my browser between yesterday and today), although it should be the 15th.

I see two possible solutions:
- easy one: to be able to click on the Today button to update the Today's date manually
- automatic one: to have an event sent by the realtime adapter to say "hey, date day has changed", and calendar automatically updates the highlighted box in this case.

Not a big deal, but attention to details is what makes the difference between a great product and an *awesome* product :)

**Comment by carrieje** [comment]
Before reading this bug, I thought my cozy calendar was not set to the correct timezone.
But after reading this issue, I tried refreshing my calendar. And the today highlight jumped from yesterday's date to today's one.

Is this bug really fixed ?

**Comment by jsilvestre** [comment]
I don't know, it's quite hard to test. If the bug occurred for you, that means it's not properly fixed. I reopen and will try to have a look at it.

**Comment by jsilvestre** [comment]
Is it possible that it worked once, but not afterwards? I have just fixed this, but I don't understand why it would not work at all :-/

**Comment by poupotte** [comment]
Il doesn't work for me :/ . I pinned my calendar yesterday, 'Today' isn't change.
