### ISSUE TITLE
Calendar selection on mobile doesn't work properly

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-calendar#182]
@frankrousseau noticed it doesn't work properly on mobile.

**Comment by clochix** [comment]
@jacquarg any news on this ?

**Comment by jacquarg** [comment]
Yes ! #193 should have fix it.

**Comment by clochix** [comment]
Thanks @jacquarg ☺ @jsilvestre or @frankrousseau can you confirm it works for you and close this please ?

**Comment by frankrousseau** [comment]
It works for me.
