### ISSUE TITLE
Calendar doesn't display new event when saved from "More Details" pop-up.

### ISSUE THREAD

**Issue by gabeos** [cozy/cozy-calendar#200]
Calendar shows events created through the simple event creation pop-up immediately, but when events are created using the additional "More details" entry window, the event doesn't show up until after I reload the page. 

Minor, but thought I'd bring it to your attn. since it's probably a minor fix :)

**Comment by frankrousseau** [comment]
Thank you notifying us about that bug. We'll fix it.

**Comment by poupotte** [comment]
Thanks for your report.

I can reproduce your issue only partially. 
Indeed, if I keep calendar in a window and I stop my application (can be stopped by autostop). I have your behaviour : events created by pop-up works well and events created by "More details" doesn't show up. After I reload I can see all my events. 
However, after this first reload, all event creations works well (pop-up or "More details").

**Comment by poupotte** [comment]
This issue should be fixed.
