### ISSUE TITLE
Share ics file

### ISSUE THREAD

**Issue by aenario** [cozy/cozy-calendar#206]
My roommate still use Google Calendar (I am a terrible evangelist). I need to share my calendar as an ICS file with a private URL and to display a remote (changing) ICS calendar inside my cozy.

Will work on it in a week-end.

**Comment by aenario** [comment]
Note : if we do both, it will also solve the shared calendar between cozy problem (read-only)

**Comment by m4dz** [comment]
Oooooh, I agree sooooooo much! I think this is definitely the way the things should be done :heart_eyes:.

**Comment by frankrousseau** [comment]
Add link to #91 and #93

**Comment by aenario** [comment]
subscribe @MartyLake

**Comment by MartyLake** [comment]
Can't wait !!! :+1: =D

**Comment by jsilvestre** [comment]
This issue is a duplicate of #91 and #93 so I'm closing it!
