### ISSUE TITLE
[GAF] Losing focus on the agenda name text field should save and/or get back to the text mode

### ISSUE THREAD

**Issue by bnjbvr** [cozy/cozy-calendar#217]
STR
===

- Create a new calendar
- Click on the right arrow (leftmost bar)
- Select "rename"
- Enter something in the text field

Expected
===

When pressing enter or focusing out the text field, it should get back to normal mode

Observed
===

It stays in edit mode.

http://b.benj.me/public/cozy-agenda-focus.png

**Comment by sylzys** [comment]
Pressing enter works for me. (Chrome 41, Mac OS).
But you're right, focusing out is not working
