### ISSUE TITLE
[GAF] Creating a new agenda should automatically select the name field

### ISSUE THREAD

**Issue by bnjbvr** [cozy/cozy-calendar#218]
STR
===

- Create a new event
- Click on the agenda bullet

Expected
===

The name of the previously auto-assigned agenda should be selected, so that we can replace it quicker.

Observed
===

It is not, and it confuses my girlfriend.

**Comment by sylzys** [comment]
Addressed by https://github.com/cozy/cozy-calendar/pull/220

**Comment by frankrousseau** [comment]
@bnjbvr Could you tell us if it's fixed?

**Comment by bnjbvr** [comment]
It is, thank you!
