### ISSUE TITLE
icon "duplicate event" is missing on popover

### ISSUE THREAD

**Issue by sylzys** [cozy/cozy-calendar#223]
The link is working, but the icon is not showing.

It's supposed to be under the 'trash' icon.

![capture d ecran 2015-03-19 a 20 17 38](https://cloud.githubusercontent.com/assets/1545358/6738857/14c4607e-ce75-11e4-93a1-66562e6f2c97.png)

**Comment by sylzys** [comment]
#227

**Comment by frankrousseau** [comment]
Thank you for reporting and for the fix.
