### ISSUE TITLE
"Email update title" not translated in english

### ISSUE THREAD

**Issue by NumEricR** [cozy/cozy-calendar#228]
Hi,

If you look at the english locales, you will notice a french string as value of "[email update title](https://github.com/cozy/cozy-calendar/blob/master/client/app/locales/en.coffee#L222)".
I think this has been forgotten while translating cozy-calendar :)

**Comment by frankrousseau** [comment]
Thank you @NumEricR for reporting.

**Comment by poupotte** [comment]
It's fixed in the new version. Thanks @jsilvestre  :)
