### ISSUE TITLE
[RWD] icons missing in top bar

### ISSUE THREAD

**Issue by sylzys** [cozy/cozy-calendar#231]
When browsing to Cozy cal on a mobile devices, some icons are missing on the top bar:

![screenshot_2015-03-30-12-04-10](https://cloud.githubusercontent.com/assets/1545358/6895519/75b3fa74-d6e1-11e4-818e-5b7b469aa895.jpg)

On the left, the "Sync" icon, on the right the "select a calendar" icon. That being said, both action are working.

Mobile config used : Galaxy S5, Android 4.4.2, Dolphin Browser.
Cozy config used : 
Data System: 1.0.27
Proxy: 1.0.13
Home: 1.0.40
Calendar -  1.0.12 
Controller: 2.0.19

**Comment by frankrousseau** [comment]
Thank you @sylzys for reporting that bug!

**Comment by jsilvestre** [comment]
@sylzys we have not been able to reproduce. Can you update your Cozy (stack and Calendar app) and try again? Thanks!
