### ISSUE TITLE
Alerts set on event on calDAV client not synchronised to cozy instance

### ISSUE THREAD

**Issue by sylzys** [cozy/cozy-calendar#233]
When setting an event on a calDAV client (here, BusyCal on Mac), the event itself (hour, length...) is synchronised on Cozy instance, but the alerts / alarms set are not.

That mean, on my computer I set an event today at 8PM, with an alert 1h before, the event appears on my Cozy Calendar, but the alert does not. The downside is, when synchronising with another device (a smartphone, e.g.), the event appears with no alert too, which is a bit painful :/

Is there a way to propagate that kind of event through calDAV ?

**Comment by frankrousseau** [comment]
I thinks it's a bug. CalDAV should handle it. Thank you for reporting.

**Comment by sylzys** [comment]
That's what I thought tbh. Even when I tried both ways, still no alarms set :/

**Comment by Beast141** [comment]
Hi Guys,  I have a similar issue.. but mine relates to NO event being synchronized to the cozy server. It seems i can only sync one way and that is from server to the client. on my android phone. but not the other way around at all.  Do you think this is also part of the bug?

Another question separate to this is.. is it possible to change default username and password on server which is currently 'me' and the random password that is always the same?

**Comment by sylzys** [comment]
@Beast141 you change the sync password by clicking on "regenerate" on sync module page. Pretty sure you can't change the username, but maybe @frankrousseau could confirm it or not.

Regarding the events, did you ahve a look at the logs to see what is happening when you try to synchronize from your phone ? You can use the Term app to open the log file (somewhere around /usr/local/cozy/apps/sync/server)

**Comment by jsilvestre** [comment]
@sylzys could you please provide me an ICS export for an event whose alarm is not synced with Cozy? Thank you.

About the user/password, sorry for the late answer. It is currently impossible to change the username (which is "me"), but you can regenerate the password as @sylzys mentioned. There is an issue I suggest you check if you want more information / want to support it: https://github.com/cozy/cozy-sync/issues/52.

**Comment by jsilvestre** [comment]
Also see https://github.com/cozy/cozy-calendar/issues/429.

**Comment by clochix** [comment]
Also see #460.

**Comment by jsilvestre** [comment]
Closed in favor of https://github.com/cozy/cozy-sync/issues/137 because it is related to synchronization.
