### ISSUE TITLE
Moment deprecation warning

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-calendar#234]
When opening Calendar, I get a deprecation warning in JS console :

    Deprecation warning: moment().add(period, number) is deprecated. Please use moment().add(number, period).

We should probably update some calls.

**Comment by jsilvestre** [comment]
@clochix do you still have this behaviour after an update?

**Comment by clochix** [comment]
Using Calendar 1.0.14 in Firefox Nightly, I still get this warning in console: “Deprecation warning: moment().add(period, number) is deprecated. Please use moment().add(number, period). at vendor.js (line 24011)”

**Comment by jsilvestre** [comment]
RMS damn me, it only triggers the warning when there are recurring events :> Thank, I'm going to look at it.

**Comment by poupotte** [comment]
It seems ok. Thanks @jsilvestre

**Comment by jsilvestre** [comment]
Apparently it's back, so I open the issue.

**Comment by clochix** [comment]
Seems related to [this issue](https://github.com/moment/moment/issues/1779#issuecomment-112607043) with `moment-timezone`.

**Comment by clochix** [comment]
Thanks @jsilvestre, no more warning in the logs, it seems resolved it this time, congrats ☺

**Comment by clochix** [comment]
If fact, I just get again the warning ☹ It's probably because of the version of `moment-timezone` inside `cozy-ical`. Shouldn't we also update cozy-ical version and our dependency on cozy-ical ?
