### ISSUE TITLE
Support SyncML

### ISSUE THREAD

**Issue by bohwaz** [cozy/cozy-calendar#24]
SyncML is a widely used open standard for data synchronization. It's available in billions of Nokia S40 phones, and in other phones as well.

See the bug report for owncloud for details: https://github.com/owncloud/apps/issues/1061

That's a must have for a calendar/contacts cloud to be able to sync with a mobile phone.

**Comment by jsilvestre** [comment]
Years have passed and this is still not on our roadmap. I close the issue because it is very unlikely we work on it, except our context changes.

It would still make a good candidate for an app!
