### ISSUE TITLE
No email being sent with 1.0.14 

### ISSUE THREAD

**Issue by koug44** [cozy/cozy-calendar#242]
Hello,

I've just installed the last version of calendar app and it seems that no email is being sent when I create an event.

I cannot confirm it was working with the previous version, as I was not using them.
I have a correctly configured account in Email app btw.

Damien

**Comment by clochix** [comment]
Hello @koug44, sorry for the delay.
The sending of email alerts doesn't use the Email application, but the SMTP server of the instance.
Are you on a seff-hosted instance, or hosted on our servers ? Is the SMTP server of the instance configured ?

**Comment by jsilvestre** [comment]
I second the question @koug44, it seems to be working well for us. If you don't provide more information, we will close the issue. Let us know, we'll be glad to help!

**Comment by koug44** [comment]
Sorry guys, I don't have access to the test environement anymore. It was with the Docker image (don't know if it's relevant)

**Comment by frankrousseau** [comment]
ok Thank you @koug44 for your answer.
