### ISSUE TITLE
Display bug

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-calendar#244]
An user reported that when she connects on his calendar application, she can't see her calendar.

![8e1de1d01f_281x500](https://cloud.githubusercontent.com/assets/1336623/7410343/3e919a82-ef2e-11e4-8866-428a01784089.png)

**Comment by jsilvestre** [comment]
This error occurs when an user tries to create a calendar that already exists. One thing has already been fixed: it cannot be done on small screens anymore.

The other problem is that message which is actually a translation key. I did a fix for that (coming in a future PR).

**Comment by poupotte** [comment]
Thanks @jsilvestre
