### ISSUE TITLE
Display current time in week calendar view

### ISSUE THREAD

**Issue by arthurlutz** [cozy/cozy-calendar#247]
It would be nice to have a small bar that shows the current time on the current day. To have a quick look at what's before and after "now".

**Comment by frankrousseau** [comment]
Yep good idea @arthurlutz. Thank you for the suggestion!

**Comment by jsilvestre** [comment]
Also see https://github.com/cozy/cozy-calendar/issues/422

**Comment by poupotte** [comment]
Week view is now removed. Thus, this issue is no more relevant
