### ISSUE TITLE
Email notifications are no more sent

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-calendar#250]
An user (Martial) and I noticed that email invitation are not sent anymore. I don't have any error in my logs. @jsilvestre can you have a look at it?

**Comment by jsilvestre** [comment]
Possible duplicate of #242

**Comment by jsilvestre** [comment]
It is currently working. If it still doesn't work for the user, it may be self-hosted without a proper postfix configuration.

**Comment by f6fvy** [comment]
It doesn't work for me either, despite being hosted on a cozycloud.cc instance :-(

**Comment by frankrousseau** [comment]
:( It's weird, it works for me. In the next version of the Cozy Home, you will be able to send us the application logs. I hope it will help.

**Comment by frankrousseau** [comment]
In fact the bug is that email notifications are no more sent.

**Comment by poupotte** [comment]
There was an error on old data-system version. @f6fvy, can you try to update your stack ?

**Comment by f6fvy** [comment]
I'm using one of your cozycloud.cc instance (upgraded to v2 by yourself I guess), and today I still don't receive any email event notification.

**Comment by clochix** [comment]
Thanks a lot @jsilvestre, now a won't have any excuse if I forget an event ;-)
