### ISSUE TITLE
Some "change stuff" buttons are shown on smaller screens, some are not

### ISSUE THREAD

**Issue by Thatoo** [cozy/cozy-calendar#252]
Related to #259 and #260

Could you explain me how to save the details of an event. Creating an event and modifying it "normaly" it's easy and quick. However, if I click on details to add a "reminder" for example, I don't know how to save. I can only click on the cross to cancel...

**Comment by frankrousseau** [comment]
Thank you @Thatoo for reporting. Can you provide us with a screenshot?

**Comment by Thatoo** [comment]
![bottom event calendar](https://cloud.githubusercontent.com/assets/464782/7895884/8017272e-06ad-11e5-9657-90244ff9aa7d.png)
![top detail event calendar](https://cloud.githubusercontent.com/assets/464782/7895885/8019b9f8-06ad-11e5-848c-a74f567be4a1.png)

**Comment by jsilvestre** [comment]
Ok thank you, it seems to be a RWD issue.

**Comment by Thatoo** [comment]
En parlant de Responsive Web Design, sur mon ordipoche sous FFOS3.0, aucun évènement ne s'affiche (à moins que seuls les événements du jour sont censé s'afficher). Et si je clique sur les deux flèches en roue (pour la synchro), impossible de revenir au calendrier.
Sorry for the language, I didn't pay attention I was writing in french, now I'm lazy to translate :-)

**Comment by jsilvestre** [comment]
Okay that is a bug. The behaviour (not being able to edit on smaller devices) is intended in order to reduce the app's complexity. The big idea is that making a calendar web app right is hard on mobile, so we just provide a minimum service (read functionnality), then you have to use a mobile app with sync to manage your calendars on mobile. I know it might sound disappointing, but we don't have the resources to make it right on mobile as of today.

**Comment by Thatoo** [comment]
ok, I guessed it right.
So "save details" on desktop version and "hide sync button" on mobile version and we are good :-)

**Comment by kelukelu** [comment]
Hi @Thatoo. 
Is 1024*600 the resolution of your laptop?
Thanks

**Comment by Thatoo** [comment]
hello @Kelukelu, yes you are right, I have a small eeepc and the best resolution I can have is 1024*600.
cheers,

**Comment by kelukelu** [comment]
Thanks @Thatoo for the quick answer :)
Have a nice evening

**Comment by Thatoo** [comment]
Well done!
The new version solves the problem, it's great!
I'll have a new request now, sorry :-) I'm opening a new issue for it.
