### ISSUE TITLE
Improve calendar's color picker

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-calendar#257]
The user should be more guided when picking a color for a calendar, i.e. reusing the ones in #256

**Comment by kelukelu** [comment]
We should propose a selection of 24 preset colors to make our users' life easier

**Comment by kelukelu** [comment]
Here is the brand new color picker (grid style):
![calendar - color picker](https://cloud.githubusercontent.com/assets/7029620/7931383/9fa7624c-0910-11e5-8a2d-e04996b20c1d.jpg)
@jsilvestre: good for you ?

**Comment by jsilvestre** [comment]
Good for me.

**Comment by frankrousseau** [comment]
From what I see of the screenshot, the pale blue is hard not dark enough. Could you change that?

Btw, the new color picker looks awesome.

**Comment by poupotte** [comment]
It's ok for me. Thanks @kelukelu :)
