### ISSUE TITLE
Wrong label for "today" in the week view (FR and EN locales)

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-calendar#266]

**Comment by jsilvestre** [comment]
This is because fullcalendar locales are only for FR and PT, and somehow it also bugs for FR. It requires a proper update of fullCalendar, and I'm not confident enough to do it in this sprint since we are going to change many things at the same time. Putting that back in the backlog for now.

**Comment by poupotte** [comment]
Today label is now hidden. Thus, this issue no longer relevant.
