### ISSUE TITLE
Review calendar's header

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-calendar#267]
*This ticket has been worked in the branch named:* __enhancement/255-sidemenu-design__

**Comment by kelukelu** [comment]
Brace yourself, new header is coming:
![screen shot 2015-06-02 at 14 26 44](https://cloud.githubusercontent.com/assets/7029620/7935852/79b09008-0934-11e5-816e-e4adc39942e9.png)
With a few changes on the calendar itself (current day's color + days from another month)

**Comment by jsilvestre** [comment]
I thought about it a bit more, and I'm not convinced by the swap between month and the buttons to select the view mode. Mostly because I hope that we can have select-boxes on month and year so we can have a "goto" feature at some point. That might be just me though, since I rarely use another view than "month".

**Comment by poupotte** [comment]
Calendar's header is better now. Thanks @kelukelu !
