### ISSUE TITLE
strange lang mix in interface

### ISSUE THREAD

**Issue by goofy-bz** [cozy/cozy-calendar#280]
Bits of English and of Portuguese in my supposed French interface :dancer: 

![todo a dia](https://cloud.githubusercontent.com/assets/858630/8006687/401518e6-0b96-11e5-9025-368e8cab8919.png)

**Comment by jsilvestre** [comment]
Thank you for the report, but I am going to clause, because it is a duplicate of https://github.com/cozy/cozy-calendar/issues/266.

Also, unfortunately, it will not be fixed anytime soon, but hopefully this summer.

**Comment by jsilvestre** [comment]
I noticed I didn't answer the "my calendar" issue: it is a user input, you can rename it. It is now properly translated, but if you had calendar before the fix, it's in english.
