### ISSUE TITLE
All-day events display broken

### ISSUE THREAD

**Issue by f6fvy** [cozy/cozy-calendar#285]
Running 1.0.15

The all-day events are not always displayed the same way, depending if the title is one word only, or composed of several words.

If the title is one word only, a thin bar is displayed.
If the title is composed of several words, the event is displayed "as usual" *but* the first word of the event is missing in the title !

**Comment by frankrousseau** [comment]
Ok @f6fvy Thank you for reporting.

**Comment by poupotte** [comment]
+1

**Comment by clochix** [comment]
@f6fvy we just published a new version of Calendar that should fix this one. Can you test it ?
Once again, thanks a lot @f6fvy for reporting and @poupotte for fixing ☺

**Comment by f6fvy** [comment]
Good for me. Thanks to both of you !
