### ISSUE TITLE
Improve calendar display on small screens

### ISSUE THREAD

**Issue by Thatoo** [cozy/cozy-calendar#290]
It is now possible to display our agenda by month week and by list on our pocket computer (at least the one running FFOS 3.0), and that's great!

1) However, if I switch to the "list display", I can't display again by month or week without exiting the app and opening it again.

2) I miss a day display. It would be nice to have calendar showing what we have day by day (24h). And, for purist who likes details, if we could have a line that shows the current time, it would be great!

**Comment by jsilvestre** [comment]
1°) The behaviour is intended, see https://github.com/cozy/cozy-calendar/issues/415 and https://github.com/cozy/cozy-calendar/issues/470

2°) I opened a separate issue for this request, thanks! See https://github.com/cozy/cozy-calendar/issues/471
