### ISSUE TITLE
Events spread on several days are not correctly displayed in list mode

### ISSUE THREAD

**Issue by f6fvy** [cozy/cozy-calendar#291]
If an event is spreading on several days, its first day only is mentioned in the list display.

**Comment by clochix** [comment]
Thanks for reporting @f6fvy, we'll have a look at this ASAP ☺

**Comment by jsilvestre** [comment]
It should be done like in Google Calendar: for each day the event is occurring, we display the event with its number (1/3, 2/3, 3/3) in the description.

First day: the starting time.
Second day: "all day".
Third day: the ending time.

**Comment by kelukelu** [comment]
This is how Google Calendar on iOS manages it:
![photo 03-07-15 09 06 26](https://cloud.githubusercontent.com/assets/7029620/8494254/77beaae0-2163-11e5-9cbf-6038ba790a75.png)

**Comment by clochix** [comment]
It works, thanks @jsilvestre for your awesome work.
@f6fvy you can switch Calendar to development branch if you want to test it now, or wait a few days until we publish a new stable version.
