### ISSUE TITLE
[Cosmetic] Empty parenthesis () in the import preview

### ISSUE THREAD

**Issue by f6fvy** [cozy/cozy-calendar#292]
When importing events, the preview displays empty parenthesis - like this () - is the event has no location. And, yes, I'm picky ;-)

**Comment by clochix** [comment]
Thanks for noticing @f6fvy, we'll fix this.

**Comment by clochix** [comment]
It's nicer now, thanks @jsilvestre ☺
@f6fvy the fix will be available in the next version of Calendar, due at the end of the week.
