### ISSUE TITLE
Local notification still active despite the deletion of an event

### ISSUE THREAD

**Issue by f6fvy** [cozy/cozy-calendar#303]
Calendar 1.0.15

- Create and save an event with a local notification time ahead.
- Few seconds later, delete this event within the app
- Despite the event deletion, the notification will pop up at the given time.

**Comment by clochix** [comment]
@poupotte I'm using development branch of cozy-home and cozy-calendar, and an alarm is still fired after I deleted the event. Does I miss something?

**Comment by clochix** [comment]
@clochix the fix has not been merged in Home yet, you'll have to wait before testing

**Comment by clochix** [comment]
The code has been merged but it still doesn't work ☹
@poupotte your fix to `server/models/event.coffee` seems to have been reverted some days later by @jsilvestre : https://github.com/cozy/cozy-home/commit/bccb0b6f844ececaae9419c2b93b3afdb35e531f
Could you find a way to fix both this one and #250 ? Thanks !

**Comment by jsilvestre** [comment]
Apparently the cleaning algorithm must be fixed, because https://github.com/cozy/cozy-home/commit/bccb0b6f844ececaae9419c2b93b3afdb35e531f#diff-2bfb954952db35a9528ac302970b0938R112 is mandatory (key formed by ID and index), so that notifications work.

Let's put that in the next sprint, we'll see together.

**Comment by poupotte** [comment]
It should be fixed with https://github.com/cozy/cozy-home/commit/48cd191045bcf1965bb7ada00c4d94c935060cf9.

**Comment by clochix** [comment]
Thanks @poupotte,
@f6fvy could you update your server to the latest version of the Cozy stack, and check that it works as you expect ?

**Comment by clochix** [comment]
Any news @f6fvy ?

**Comment by f6fvy** [comment]
Sorry for this late reply.

Fixed for me now.

Thanks !
