### ISSUE TITLE
Some recurring events are buggy at import.

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-calendar#305]
@frankrousseau gave me an ics with buggy events, something about rrule.

**Comment by jsilvestre** [comment]
Reopened because it's not published yet, so we cannot confirm it actually works in calendar ;-)

**Comment by clochix** [comment]
@jsilvestre What's the status of this ticket ? Has it been published now ?

**Comment by jsilvestre** [comment]
It's been published for a while, yes.

**Comment by clochix** [comment]
Thanks :-)
