### ISSUE TITLE
Disparition of cal-header on responsive list view

### ISSUE THREAD

**Issue by PetiPandaRou** [cozy/cozy-calendar#306]
When I'm using my mobile phone (or when I resizing my desktop browser window), the cal-header disappears in list view whereas is still present in other view (month and week views).

**Comment by clochix** [comment]
This was pretty annoying, preventing to go back to month view from list view. Your fix works just perfectly, thanks @PetiPandaRou. I hope this is the first of a long list of contributions ☺

**Comment by PetiPandaRou** [comment]
Thanks Clochix.
I hope so :)
