### ISSUE TITLE
[Suggestion] Narrow time column in week view

### ISSUE THREAD

**Issue by f6fvy** [cozy/cozy-calendar#308]
In week view, the time column (left) is rather wide (with unused wasted space), especially when used with a phone in portrait orientation. The gained area would allow a more comfortable reading of the events.

**Comment by clochix** [comment]
Thanks for reporting @f6fvy, we'll try to improve this soon ☺

**Comment by poupotte** [comment]
Week view has been removed, so, this issue is no more relevant.
