### ISSUE TITLE
Requests for event after its deletion

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-calendar#315]
Looking at the network traffic, I just noticed that when I delete an event, the server send two GET requests after the delete : 
 - DELETE xxx.cozycloud.cc/apps/calendar/events/73e06aa0f9c65df7a228bd4662096944?sendMails=false → 200
 - GET xxx.cozycloud.cc/apps/calendar/events/73e06aa0f9c65df7a228bd4662096944?sendMails=false → 404
 - GET xxx.cozycloud.cc/apps/calendar/events/73e06aa0f9c65df7a228bd4662096944?sendMails=false → 404

**Comment by jsilvestre** [comment]
It's not the case anymore, I close the issue.
