### ISSUE TITLE
When creating a new calendar the name of calendar to set is not the right one

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-calendar#319]
Hi,

when I create a new calendar (I already had 2 calendars), the client proposes to set the name of a calendar, but it is not the name of the new calendar which is proposed, but the name of the last calendar in the list before creating it. A picture is better than a long description: 
![image](https://cloud.githubusercontent.com/assets/7999082/8567449/ae7007cc-2565-11e5-9927-46d3eb839c69.png)

Other side effect, the color of the calendar is changed.

**Comment by jsilvestre** [comment]
Hello @ZeHiro , thank you for the report.

We are aware of this, but we won't be able to fix it independently of a big refactoring (see https://github.com/cozy/cozy-calendar/issues/316). Sorry for the inconvenience, hopefully it'll go as a priority.

**Comment by ZeHiro** [comment]
Well it's not a problem for me, but for new users ;)

**Comment by clochix** [comment]
Hi @ZeHiro,
I think it has been fixed, could you give a try to the latest version of the application ?

**Comment by ZeHiro** [comment]
Perfect, thanks @clochix (and others)
