### ISSUE TITLE
Wrong calendars colors in the list on the left

### ISSUE THREAD

**Issue by vialibre** [cozy/cozy-calendar#328]
Since last update 1.0.18, the colours of the badges are wrong in the left menu list when loading the page. The inline css of the "badge" span is wrong.

Clicking twice on the colour dot to disable/enable the calendar restores the right colour.

**Comment by clochix** [comment]
Thanks for reporting this @vialibre, we'll fix this soon ☺

**Comment by clochix** [comment]
Hi @vialibre,
Could you install the new version of Calendar (1.0.19) and test if you still encounter this bug ? Thanks !

**Comment by vialibre** [comment]
This fixed the issue. Thanks.

**Comment by clochix** [comment]
Thanks for reporting and confirming :-)
