### ISSUE TITLE
Problem syncing with davdroid

### ISSUE THREAD

**Issue by krichtof** [cozy/cozy-calendar#329]
I encounter some problems with my android calendar which is connected via DavDroid to cozy calendar.
It worked 2 or 3 weeks ago.
But now, I don't see new events created in some other devices (via Calendar on my mac or via the cozy-calendar webapp)

Anyone has the same issue ? 

Thanks a lot.

**Comment by clochix** [comment]
Hi @krichtof,
It's hard to investigate without logs. Are you self hosted, or using a beta-test instance on our servers ? If you're self hosted, could you send the logs of Sync and Calendar apps to support at cozycloud.cc ? Otherwise, I'll have a look on your server.

Thanks for reporting !

**Comment by clochix** [comment]
Hi @krichtof,
Any news on this ? If you still encounter this problem, could you provide us some logs ? Thanks !

**Comment by krichtof** [comment]
Sorry to reply now. Holidays, holidays ;)
I'm using a beta-test instance on your servers. I don't encounter the problem anymore.
Sorry not to be precise on my bug description. Then android message during synchronization was about ssl problem. But as I said, i don't have the problem now.

No problem for me if you close the bug !

**Comment by frankrousseau** [comment]
OK thank you @krichtof for reporting!
