### ISSUE TITLE
Some german translation files are missing

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-calendar#330]
A user [reported on forum](https://forum.cozy.io/t/missing-german-jade-files-for-calendar/1023) that when instance language is German, the application fail to start. We should ensure that missing translation file don't make the application crash.

**Comment by jsilvestre** [comment]
It's https://github.com/cozy/cozy-calendar/blob/master/server/libs/localization_manager.coffee#L46-L49. I'm going to fix that.

**Comment by poupotte** [comment]
Even if translation file is missing server doesn't crash now. Thanks @jsilvestre
