### ISSUE TITLE
Sort calendars

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-calendar#331]
Calendar sort order seems to be random. Could we sort them ?

**Comment by f6fvy** [comment]
What if the user could order the list by himself (drag'n'drop items ?) ?

**Comment by clochix** [comment]
“the best is the enemy of the good” ;-) Let's first try to fix the display order, so it's no more random. Allowing to drag and drop calendars would make the UI and the code more complicated. Let's keep this simple.
