### ISSUE TITLE
Multi day Event not displayed on the last day when it ends before 9:00

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-calendar#342]
If I set the end of a multiday event at 8:59 (morning) it is not displayed on the last day on the calendar. If I set it at 9:00, it is. Is it a design choice? 
Shouldn't this be parametrable (by calandar would be perfect :smiley:  )?

**Comment by clochix** [comment]
Thanks for reporting @ZeHiro,
@jsilvestre could you elaborate on this, please ?

**Comment by jsilvestre** [comment]
It's probably a bug. I change the label to match that feeling.
