### ISSUE TITLE
Allow to add exceptions to recurring events

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-calendar#344]
As requested in [this post](https://forum.cozy.io/t/calendar-quelques-retours/875/31).
Depends on cozy/cozy-ical#36

**Comment by poupotte** [comment]
Related to https://github.com/cozy/cozy-calendar/issues/238

**Comment by jsilvestre** [comment]
Since it's a duplicate of #238, I close this issue and links this one to the original one.
