### ISSUE TITLE
Improve closing of popins windows

### ISSUE THREAD

**Issue by f6fvy** [cozy/cozy-calendar#345]
When creating a new event, by default the focus is on the title edit field. If you click the "more options" button, the focus is lost. Consequently, at that time, you can't use the Escape key anymore to dismiss the dialog. (1.0.19).

**Comment by clochix** [comment]
Thanks for reporting @f6fvy, we need to improve how we close this window. Even when Esc works, we can't expect the user to guess this behavior. We should at least add a close icon, maybe also a second button to close it without saving. What do you think ?

**Comment by f6fvy** [comment]
Clearly, at least a "Cancel" button is desirable, and could be useful also for the non-desktop versions. However, the Esc key possibility must remains. This should applies as well on the "Sync options" screen.

**Comment by clochix** [comment]
We should add a close icon and a cancel button to both the detail and the sync windows.

**Comment by clochix** [comment]
It works fine, thank you !
