### ISSUE TITLE
All day event broken after last update

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-calendar#349]
Since last update, one of my event is broken. See: ![calendar_broken_dallday_event](https://cloud.githubusercontent.com/assets/568111/8904918/bff0a56c-3463-11e5-9469-5e7ea87819bb.png)

Please note that the event should be on the 9th. It is actually on the 9th, but as soon as I click it, it goes to the 10th (it's not saved though). And the popover also looks broken.

Here is the related .ics:
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Cozy//NONSGML Cozy Calendar//EN
X-WR-CALNAME:cozy
BEGIN:VEVENT
UID:b48a1f9afa716d158ab3f8bbf292fbea
DTSTAMP:20150602T123126Z
DTSTART;VALUE=DATE:20150709
DTEND;VALUE=DATE:20150710
CREATED:20150602T123126Z
LAST-MODIFIED:20150602T123126Z
SUMMARY:Réunion d'équipe
END:VEVENT
END:VCALENDAR
```

**Comment by clochix** [comment]
Hi @jsilvestre,
Could you check if it has been fixed ?

**Comment by poupotte** [comment]
This issue is fixed. Thanks @clochix
