### ISSUE TITLE
There is no message in case of unsaved change

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-calendar#351]
If an user does a modification, and close without saving, there is no message to prevent the user from doing that by mistake, thus losing its modification.

It could be done through a screen o/

Also, in the same vein, if you change, say the repeat mode, the model in the app is changed and the modifications are shown on the screen, whereas they are not persisted yet. The popover's model should be a clone of the actual model to prevent that.

**Comment by jsilvestre** [comment]
Also see https://github.com/cozy/cozy-calendar/issues/404

**Comment by poupotte** [comment]
This issue is now fixed (version 1.0.37)
