### ISSUE TITLE
New event popup partially hidden on week view

### ISSUE THREAD

**Issue by nicodel** [cozy/cozy-calendar#362]
Cozy instance hosted on Cozy Cloud infrastructure (nicolas-6)
Data System: 2.0.6
Proxy: 2.1.0
Home: 2.0.6
Controller: 2.0.29
calendar -  1.0.19

### Step to reproduce:
1. Open the Calendar application.
2. Select the Week view
3. Click on the Monday column (whatever time).

### What happens:
1. New event popup appears, but is half hidden on the left side of the browser window (whatever window size is):
.
![calendar-1](https://cloud.githubusercontent.com/assets/1799460/9083750/364f12ce-3b6d-11e5-8c97-b2f5985be27f.PNG)
![calendar-2](https://cloud.githubusercontent.com/assets/1799460/9083751/36574a84-3b6d-11e5-8e66-56b3cb9bb381.PNG)

### What should happened:
1. Just like on the Month view, popup window should be on the right side on the select day:

![calendar-3](https://cloud.githubusercontent.com/assets/1799460/9083786/7a6dd328-3b6d-11e5-8e1b-96f628752924.PNG)

**Comment by clochix** [comment]
Thanks for reporting @nicodel, we'll do our best to fix this ASAP.
@jsilvestre heeeeeelp !!!

**Comment by nono** [comment]
FYI, bootstrap v4 uses [tether.js](http://github.hubspot.com/tether/) for their tooltips.

**Comment by nicodel** [comment]
I just updated Calendar to 1.0.24, and this is fixed. Thanks !
