### ISSUE TITLE
Default event duration not the same on Week and Month View

### ISSUE THREAD

**Issue by nicodel** [cozy/cozy-calendar#364]
Cozy instance hosted on Cozy Cloud infrastructure (nicolas-6)
Data System: 2.0.6
Proxy: 2.1.0
Home: 2.0.6
Controller: 2.0.29
calendar - 1.0.19

When use create an event from the Month view the default duration on the event is one hour, but when user create an event from the Week view, the default event duration is 30 minutes.
It would be better to have the same value in both cases in order to not confuse the user.

**Comment by clochix** [comment]
Thanks for reporting, I'm fixing it ASAP :-)

**Comment by poupotte** [comment]
It orks well now, thanks @clochix !
