### ISSUE TITLE
Hour fields are broken

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-calendar#376]
Hello there,

I found a very annoying bug in the new version of the Calendar application.

1°) When I click on the hour field of the creation modal, it opens the date field. When I click a lot on the hour field, it finally selects it. 

2°) Then another bug occurs, when I change the beginning hour, the end hour is not updated.

**Comment by jsilvestre** [comment]
I edited your message to separate the two bugs.

1°) I have not been able to reproduce with neither Chrome or Firefox. Could you check again, and provide more information please?

2°) I'm going to fixed it.

**Comment by frankrousseau** [comment]
The update of the hour fields is still broken. It works well for the start hour field but the end hour field goes crazy after a modification of the start field.

**Comment by frankrousseau** [comment]
Fixed
