### ISSUE TITLE
Problem authenticating with Apple Calendar

### ISSUE THREAD

**Issue by krichtof** [cozy/cozy-calendar#378]
I've got this message tonight when using Apple Calendar : 

> Calendrier ne parvient pas à se connecter au compte geek.cozycloud.cc

And when I type my password (which works via webapp), I've got : 

> Le serveur a répondu par une erreur

Thanks for your help !

**Comment by krichtof** [comment]
No more authenticating problem. There was a problem with your server yesterday ?

**Comment by frankrousseau** [comment]
It looks like your data system was restarted. So, all your stored password cannot be read by your apps (including the CalDav server) until you log in to your Cozy. It's because your password is used to encrypt/unencrypt passwords stored by apps.

**Comment by krichtof** [comment]
Sorry. I didn't mention that my calendar is hosted on your beta instance server.
The data system of the beta instance server was restarted yesterday ? Right ?

**Comment by frankrousseau** [comment]
Probably, I met this issue too. I wil ask to our infrastructure team.

**Comment by clochix** [comment]
@frankrousseau any news from the infra team ? I just had a look at the logs of @krichtof's instance, and didn't see any error on August 16.
@krichtof have you encountered again the same issue in the last weeks ?

**Comment by jsilvestre** [comment]
I'm closing since nobody reported this issue since then; @krichtof if you still run into the issue, please feel free to reopen!

**Comment by krichtof** [comment]
I don't run into this issue, so ok for me :)
