### ISSUE TITLE
Wrong position of the event modal

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-calendar#382]
A forum user reported that the modal has a wrong position in some cases (non easy to reproduce).

https://forum.cozy.io/t/calendar-bug-left-slide-move-on-month-view-no-clear-reproducibility/1147/2

**Comment by poupotte** [comment]
From [forum](https://forum.cozy.io/t/calendar-bug-left-slide-move-on-month-view-no-clear-reproducibility/1147/3), this issue seems fixed ! @frankrousseau , can I close it ?

**Comment by frankrousseau** [comment]
Yes, thank you!
