### ISSUE TITLE
When I send an invitation, the attached event is not correct

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-calendar#383]
When an user sends a calendar invitation, the ics file attached to the event has errors:

* The hour is not properly set (probably a timezone issue) ;
* When the user adds it to its Google Calendar, it creates invitations again for the other users (invitation from Google Calendar).

**Comment by frankrousseau** [comment]
@jsilvestre It looks to work better but the Organizer is marked as undefined on Google Calendar. Do you think that something could be done for that like adding a field into the generated ics event?

**Comment by jsilvestre** [comment]
Ah yes, it's not something we actually do at all. Let me fix it.
