### ISSUE TITLE
List view : Incorrect all day events

### ISSUE THREAD

**Issue by f6fvy** [cozy/cozy-calendar#397]
Calendar 1.0.24

A two days all-day created event is spread on three days in the list view.

![bugcalendar](https://cloud.githubusercontent.com/assets/12431844/9657948/cbf1a9c4-5245-11e5-9ee1-1311161d26b0.png)

**Comment by clochix** [comment]
Fixed in a1e1dd4 (wrong ticket number in commit)

**Comment by poupotte** [comment]
Thanks @clochix . This issue is well fixed for me !
