### ISSUE TITLE
keyboard navigation in creation popup

### ISSUE THREAD

**Issue by Benibur** [cozy/cozy-calendar#401]
when creation an event, when you change the focus with the "TAB" key never enters in the "add a participant" button, nor the other options (alerts, repetition).
the order of the focus is strange : place => cancel => description => save => and then it should cycle 

by the way : when the focus is on "cancel", right arrow should put focus on "save".

the focus order should take into account if the options are displayed or not.

**Comment by poupotte** [comment]
It's better than before but I have two remarks:

* If I go to`Add participants`, I can add participants with keyboard but I didn't find how validate it (to come back on event) with keyboard.
* If I select `more options`, it should be nice to navigate with 'tab' in these options.

@clochix , what do you think about that ?

**Comment by clochix** [comment]
Once it has been merged, you'll be able to : 
 - navigate to the Done button in title bar with Shift-Tab. Not very nice, maybe we should add another Done button at the bottom ?
 - when clicking on `more options`, the focus goes to the description field.

**Comment by clochix** [comment]
@Benibur this should have been fixed, can we close this ?
