### ISSUE TITLE
the date of an occurence of a serie of events is wrong

### ISSUE THREAD

**Issue by Benibur** [cozy/cozy-calendar#403]
1/ create a weekly event, starting today, save
2/ click on the second occurence next week
=> in the popup the date will be today instead of next week.

**Comment by clochix** [comment]
This happens for all recurring events : there's only one event, whose date is the starting point of the recurrence. So when we edit the event, we always display the starting date, not the date of this specific occurrence.

Updating the date of a recurring event doesn't really make sense, so I suggest we disable the editing of start and end dates, except on the first occurrence. 

What do you think?

**Comment by jsilvestre** [comment]
We created a mega-issue about recurring events. See https://github.com/cozy/cozy-calendar/issues/583.
