### ISSUE TITLE
escape in a modified popup should ask for confirmation before closing

### ISSUE THREAD

**Issue by Benibur** [cozy/cozy-calendar#404]
1/ open an event popup (creation or modification)
2/ press esc
=> the popup is closed, it is fine.

1/ open an event popup (creation or modification)
2/ modify something (title)
3/ press esc
=> the popup is closed, it is not fine.

**Comment by poupotte** [comment]
Related to https://github.com/cozy/cozy-calendar/issues/351

**Comment by jsilvestre** [comment]
Since it's a duplicate of #351, I close and link to this issue.
