### ISSUE TITLE
Disparition of cal-header on responsive view

### ISSUE THREAD

**Issue by PetiPandaRou** [cozy/cozy-calendar#407]
This bug is quite similar to bug https://github.com/cozy/cozy-calendar/issues/306.
But now, the header is not visible anymore, month, week and list.

**Comment by clochix** [comment]
Thanks for reporting @PetiPandaRou, where is the patch ? :-P (joking, the fix is ready)

**Comment by PetiPandaRou** [comment]
@clochix sorry, I sleep well now. On my next insomnia, I will do a localisation patch, I promise ;)

**Comment by frankrousseau** [comment]
That was not a bug. The month view is broken with mobile. That's why we don't want to display it.

**Comment by jsilvestre** [comment]
This issue has not been closed, but indeed it was intended and the behaviour will be restored, as stated in #415.

I also opened a new issue to remind us that at some point we'll have to make the UI completely responsive: https://github.com/cozy/cozy-calendar/issues/470
