### ISSUE TITLE
Remove "week - month - list" header for small resolution

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-calendar#415]
Month and week views don't work properly on small screens. We should remove the access to this view until we find a proper UI for them.

**Comment by aenario** [comment]
Not sure if we are talking about the same thing, but I think @clochix just did the opposite of that because of user demands : 
https://github.com/cozy/cozy-calendar/issues/306
https://github.com/cozy/cozy-calendar/issues/407 

May be we should ask this user about the use-case ?

**Comment by frankrousseau** [comment]
Yes it will be interesting. But I think the use case is legitimate. The problem is that we don't have time to make it work properly.

**Comment by Aryess** [comment]
:+1:

**Comment by roukydesbois** [comment]
+1

**Comment by poupotte** [comment]
"week - month - list" header is hidden for small screen on new Calendar version (1.0.37)
