### ISSUE TITLE
Add a “share” item to calendar menu

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-calendar#421]
For now, in the menu of each calendar, we have an “import” item. It would be nice to add an “share” item that open the sync modal.

**Comment by jsilvestre** [comment]
Do you mean with the link to sync only this calendar? Or to be able to share an ICS feed for the calendar?

**Comment by clochix** [comment]
Yes, it's related to the most requested feature of allowing to share a read-only link to a calendar. I think this ticket can be closed and merged into the main issue.

**Comment by jsilvestre** [comment]
Thank you!
