### ISSUE TITLE
Notification not sent for event created outside Cozy

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-calendar#429]
As [reported by a user](https://forum.cozy.io/t/calendrier/364/34).

When one create an event in another calendar client and synchronize it with Cozy, no email alarm are sent.
We should create notification when syncing.

**Comment by jsilvestre** [comment]
Also see https://github.com/cozy/cozy-calendar/issues/460.

**Comment by jsilvestre** [comment]
This is a duplicate of https://github.com/cozy/cozy-calendar/issues/233.
