### ISSUE TITLE
Missing french translation in the web UI

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-calendar#432]
Hello,
here are the missing translations in the french webUI:
- Above the list of calendars, "Calendars" is used -> Calendriers/Agendas
- "Synchronization" button -> "Synchonisation" 
- When creating a new event : 
 *  placeholder for event title "Event title" -> "Nom de l'évenement"
* Date management : "From" -> "De" / "To" -> "à" / "All day" -> "Jour complet"'/"Toute la journée"
* "Place" -> "Emplacement"/"Localisation"
* "Add guest" -> "Inviter"
* "More Options" -> "Plus d'options".
* "Save" -> "Sauvegarder"
* ""Description" -> "Déscription"
* "No alert" -> "Pas d'alarme" / "Pas de rappel"

I won't translate all because it's long, but it seems most of the components are untranslated. All sub menu (alert management/guest invitation/repetition management) shall be tranlated also.

**Comment by clochix** [comment]
Thanks for reporting @ZeHiro

**Comment by ZeHiro** [comment]
@clochix 
In fact an import of translations from trnsiflex is enough

**Comment by clochix** [comment]
Ok, thanks ☺

**Comment by poupotte** [comment]
This issue is now fixed.
