### ISSUE TITLE
Sundays event are not displayed when switching to other week

### ISSUE THREAD

**Issue by Nephos** [cozy/cozy-calendar#434]
Hello

In the calendar, on the week view, when I click to an arrow to the next / previous week, the events on sunday (last day of the week) are not displayed.

Sundays events also vanish when I go to the next then go back the the first week

They are when refreshing the page.

**Comment by clochix** [comment]
Thanks for reporting!

**Comment by Nephos** [comment]
Note: It also happens when I add a new event (anywhere on the planning).

I load my planning
![cozy-bug-3](https://cloud.githubusercontent.com/assets/979584/10951846/06d6805c-8340-11e5-90f2-325b8079c022.png)

I add a new event
![cozy-bug-4](https://cloud.githubusercontent.com/assets/979584/10951858/15211fe6-8340-11e5-9914-be12ecd5cb47.png)

**Comment by jsilvestre** [comment]
Also see https://github.com/cozy/cozy-calendar/issues/443.

**Comment by poupotte** [comment]
We removed week view on new calendar version (1.0.37). Thus, this issue is no more relevant.
