### ISSUE TITLE
tag.color format sin't consistent

### ISSUE THREAD

**Issue by jacquarg** [cozy/cozy-calendar#435]
tag.color may be:
* a color hash '#2979FF' , on calendar creation
* css rbg : rgb(41, 121, 255) , on change color on calendar 

Keeping the #2979FF form would be really handier to use the tag's color in other apps, as it's easier to parse, or convert to integer format.

**Comment by clochix** [comment]
@jsilvestre would you mind having a look at this one when you find some time? This is causing issues in the mobile app. Thanks!

**Comment by clochix** [comment]
@jacquarg This should have been fixed, could you give it a try?

**Comment by jacquarg** [comment]
Good for me thanks !
