### ISSUE TITLE
Display by list bug

### ISSUE THREAD

**Issue by Nephos** [cozy/cozy-calendar#436]
When I added the event (every weeks repetition), I got an error on the list view (18h-18h instead of 18h-20h)

![cozy-bug-2](https://cloud.githubusercontent.com/assets/979584/10884495/92f9b38e-8178-11e5-9562-2a7265f8b54d.png)
![cozy-bug-1](https://cloud.githubusercontent.com/assets/979584/10884494/92f869fc-8178-11e5-8471-71d02d1b7d0b.png)

I can reproduce the bug every times I create a new event with a weekly repetition

**Comment by clochix** [comment]
Thanks for reporting @Nephos, we'll fix that!

**Comment by jsilvestre** [comment]
It appears to be fixed, so I close. Feel free to reopen if it's not the case @Nephos, if possible with the event's ICS!
