### ISSUE TITLE
Creating an element doesn't respect the time range selected

### ISSUE THREAD

**Issue by Nephos** [cozy/cozy-calendar#439]
When I select a time range on the planning, I can insert an event.

But the popup is not initialized with the right values.

It only uses the time of the 
![cozy-bug-6](https://cloud.githubusercontent.com/assets/979584/10951997/ac908574-8340-11e5-8fac-bd88d637f56a.png)
event's beginning, but not its end (by default, is is set to begin + 1 hour)

**Comment by Nephos** [comment]
Maybe I'm wrong, but I think it's there: https://github.com/cozy/cozy-calendar/blob/master/client/app/views/calendar_view.coffee#L211

```coffee
    onSelect: (startDate, endDate, jsEvent, view) =>
      # ...
            # set default event duration to 1h
            endDate = startDate.clone().add 1, 'hour'
```
Shoud it use endDate instead of startDate +1 ?

**Comment by clochix** [comment]
Thanks for reporting @Nephos.
You're right, when you select a time range, we should use it instead of the default duration of one hour.

**Comment by poupotte** [comment]
This issue is no more relevant with new version.
