### ISSUE TITLE
Import iCalendar button does not have the right cursor

### ISSUE THREAD

**Issue by nicofrand** [cozy/cozy-calendar#442]
**With Chrome only**

In the synchronization popup the "Select an iCalendar file"  button cursor is incorrect.
It should have the same cursor than "Show" or "Export your calendar" buttons above, which is a little hand that says the button is clickable (like a link).

**Comment by clochix** [comment]
Thanks for noticing @nicofrand, this is a bug in Chromium that will soon be fixed ☺

**Comment by nicofrand** [comment]
Instead of using a weird webkit only propert, I think that transforming the span inside the div.btn into a label with the attribute for equal to the input id (import-file-input) would be a cleaner solution and the weird "opacity: 0.1" on the input could be replaced by "display: none".

**Comment by clochix** [comment]
@nicofrand This should have been fixed, could you give it a try (unfortunately, not with your clean solution, feel free to propose a PR).

**Comment by nicofrand** [comment]
Looks good to me ! I bookmark this issue to think about the PR later :).
