### ISSUE TITLE
Regression : Reminder text

### ISSUE THREAD

**Issue by f6fvy** [cozy/cozy-calendar#445]
Calendar 1.0.29 / Home 2.1.0

The reminder text of an event (on the home page) is now "Reminder" (not localized), instead of the event title as it was in the previous versions.

**Comment by clochix** [comment]
Thanks for reporting @f6fvy.
@jsilvestre is this the issue you fixed yesterday?

**Comment by jsilvestre** [comment]
Indeed, it will be fixed in the next release of application "Home".

**Comment by clochix** [comment]
Thanks to bot of you, I close this one ☺
