### ISSUE TITLE
Clicking on the arrow of an event description does nothing

### ISSUE THREAD

**Issue by nicofrand** [cozy/cozy-calendar#446]
**Steps to reproduce:**

0. Open an event
0. Click on the arrow on the right of the description

![cozy-calendar-desc](https://cloud.githubusercontent.com/assets/3419050/11531950/d116f51a-9900-11e5-94cd-fead8cbf9df7.png)

**What I expect:**

The description panel is opened (like when I click on the "Description" label).

**What happens:**
Nothing

**Comment by jsilvestre** [comment]
Can we close the issue?

**Comment by clochix** [comment]
It works for me, @nicofrand ?

**Comment by nicofrand** [comment]
I confirm everything is fine now.
