### ISSUE TITLE
The label of an event description save button is not truncated

### ISSUE THREAD

**Issue by nicofrand** [cozy/cozy-calendar#447]
There is an issue using the french locale with the "Done" button:

![cozy-calendar-desc](https://cloud.githubusercontent.com/assets/3419050/11532029/41fbf88e-9901-11e5-8fa3-f6f4f2dbe213.png)

**Comment by jsilvestre** [comment]
Can we close the issue?

**Comment by clochix** [comment]
Seems to work, I close it. @nicofrand, thanks for reporting, don't hesitate to re-open if it's not ok for you

**Comment by nicofrand** [comment]
I confirm everything is fine now.
