### ISSUE TITLE
Wrong date range displayed after switching range date

### ISSUE THREAD

**Issue by nicofrand** [cozy/cozy-calendar#449]
**Steps to reproduce:**

Expected you chose "month" by default, you are displaying the current (December) month.

0. Click on "list"
0. Click on "week"
0. Click on "month"

**What happens:**

0. List: nothing special
0. Week: from Nov 30 to Dec 06
0. Month: November is displayed (I guess it took the beginning month of the previous week display)

**What I expect:**

Month: the current (December) month is displayed.

**Comment by jsilvestre** [comment]
This bug doesn't occur anymore, so we close.
