### ISSUE TITLE
Wrong sort in list display

### ISSUE THREAD

**Issue by nicofrand** [cozy/cozy-calendar#450]
**Steps to reproduce:**

0. Open Calendar in list view
0. Notice the first event, for example "A"
0. Click on "Display previous events" (it only happens when this is done)
0. At the end of the events list, the event "A" is duplicated, and stays there even after scrolling down

![cozy-calendar-desc](https://cloud.githubusercontent.com/assets/3419050/11532536/bb3c0164-9904-11e5-918d-908a601cb151.png)

Notice: the screenshot is truncated, "Dimanche 4 septembre" is not the first event of the list.

We might not always see the event "A" at the end, but using the DOM inspector we can look at the last div.dayprogram element and notice that it is a duplicate of "A".

**What happens:**

An event from 2015 appears after the events of 2016.

**Comment by gregorylegarec** [comment]
This issue is pretty hard to reproduce. I have not been able to see it in my development environment.

**Comment by nicofrand** [comment]
I can still reproduce it. It seems like it appends an old event at the end of the page and then it fetches other events (in the future), that will replace the old event.

**Comment by gregorylegarec** [comment]
__Reproduce :__
* Create an event over more than one day. Make it the nearest in the future so it will appear in the first position in the list view
* Switch to list view
* Click on "Display previous events"
* A empty event having the same date as our newly created event appears at the end of the event list

__Expected behaviour__ :
No empty event should appear

**Comment by poupotte** [comment]
This issue will be fixed in new calendar version
