### ISSUE TITLE
Do not change calendar name/color unless anything really changes

### ISSUE THREAD

**Issue by nicofrand** [cozy/cozy-calendar#452]
**Steps to reproduce:**

0. Open a calendar's options
0. Click on "rename"
0. Press the <kbd>End</kbd>
0. Press Esc.

**What happens:**

As soon as I pressed <kbd>End</kbd> the color changed.
When I press <kbd>Esc</kbd> the spinner is displayed and the name of the calendar appears to be modified (I can check it within the logs) whereas the name stayed the same…

**Comment by poupotte** [comment]
This issue is now fixed.
