### ISSUE TITLE
Error setting hours of a recurring event

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-calendar#457]
Create a new event, make it recurrent, come back to the main event panel:
 - hours are now displayed in 12h format (with AM/PM);
 - clicking on the field display an hour helper (like the calendar) that I'm unable to remove;
 - sometime, I'm unable to change the start date: the value is reseted every time I quit the field.

This only happens on recurring events.

**Comment by jsilvestre** [comment]
Also see https://github.com/cozy/cozy-calendar/issues/466.

**Comment by jsilvestre** [comment]
We created a mega-issue about recurring events. See https://github.com/cozy/cozy-calendar/issues/583.
