### ISSUE TITLE
Wrong start hour on week view

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-calendar#458]
A user is reporting that on week view, some events (recurring ?) are not displayed at the right start hour: an event starting at 14h is displayed at 15h (the start hour is right on month view and when editing the event).

**Comment by Niols** [comment]
I do have the same problem.
Here is a more precise description on how I can encounter this:

- Select week view
- Create an event, just fill in its name, and click "save". The event is displayed correctly
- Select the event, "more options", change "no repeat" to "every week" then click "done" and "save". The event is displayed one hour after.

I am using a cozycloud.cc instance. I stay available for more details

**Comment by Niols** [comment]
Note: this is also the case in list view, where I only see elements of the form:

    [wrong_start_hour : wrong_start_hour] title

(Note that there's two times the wrong **start** hour).

**Comment by clochix** [comment]
Thanks for providing steps to reproduce, it will help us fix this issue :-)

**Comment by clochix** [comment]
Also probably related: #433 and #457

**Comment by clochix** [comment]
Another user report: “I have a problem with hours of recurring events: in week view, they are displayed at the right time, but displayed with AM/PM, but on month view they are displayed two hours earlier (and with AM/PM)”

**Comment by poupotte** [comment]
This issue is no more relevant with new version.
