### ISSUE TITLE
Notifications set from calendar app not raised on caldav clients

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-calendar#460]
If I create an event in calendar application and set a notification (Cozy Notification), the notification is not raised on my smartphone. 
I would expect the notification created in the calendar app to be transfered to the Caldav event, and raised on my smarphone

**Comment by ZeHiro** [comment]
Goes well with #429

**Comment by clochix** [comment]
Hi @ZeHiro,

Thanks for reporting, you're right, this is related to #429, we need to synchronize VALARM from and to the other client. Maybe should we open an issue in cozy-mobile. @jacquarg, any thought?

**Comment by jacquarg** [comment]
@clochix , it's not released yet, but it will work. No need for a issue on cozy-mobile yet ; )

**Comment by ZeHiro** [comment]
@clochix : should we open a ticket on sync?

**Comment by clochix** [comment]
@jacquarg \o/ Thanks !
@ZeHiro no, let's just keep this one.

**Comment by jsilvestre** [comment]
Investigating this issue might lead to a problem in https://github.com/cozy/cozy-home.
