### ISSUE TITLE
Error Polyglot in mails

### ISSUE THREAD

**Issue by Peltoche** [cozy/cozy-calendar#461]
I have set an event with a reminder by mail. The mail is ok but it contain juste the Polyglot keywords:

- from: no-reply@cozycloud.cc
- subject: reminder title email expanded
- content: reminder message expanded

**Comment by clochix** [comment]
Thanks for reporting @Peltoche.
This alarms are sent by the Home, so I just opened cozy/cozy-home#631 and will close this one.
