### ISSUE TITLE
Bug with place set by the macOS calendar app

### ISSUE THREAD

**Issue by EtienneM** [cozy/cozy-calendar#463]
Using the calendar app on MacOS, if I modify the place of an event, it automatically suggest some address to display a small map. If I use the suggested place, I can see it on the web app on Cozy but without any blank space between the street name and the city. Probably because the MacOS calendar app use a newline character that you remove when updating the place? 

The problem is that this event on my MacOS calendar app, after syncing with my cozy, do not display the place event I just set. Even though the correct place is displayed on my Cozy web page.

PS: I am using a cozy on your infrastructure at titizebioutifoul.cozycloud.cc

**Comment by clochix** [comment]
Thanks for reporting @EtienneM !

**Comment by jsilvestre** [comment]
Hello, thank you for the reporting.
This is actually a synchronization issue, I opened an issue on the relevant repository: https://github.com/cozy/cozy-sync/issues/106.

I close the issue here, but it's been taken into account.
