### ISSUE TITLE
Events of each day are sorted in reverse order

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-calendar#464]
On list view, events on each day are sorted on reverse order.

**Comment by jsilvestre** [comment]
I can't reproduce this, the order is chronological from top to bottom.

**Comment by clochix** [comment]
Yes, but it's a little bit disappointing, I expected days to be sorted in reverse chronological order, but event on each day in chronological order.
I mean, we have:

 - Monday
    - 14:00 : xxx
    - 09:00 : xxx
 - Tuesday
    - 14:00 : xxx
    - 09:00 : xxx

and I expected

 - Monday
    - 09:00 : xxx
    - 14:00 : xxx
 - Tuesday
    - 09:00 : xxx
    - 14:00 : xxx

**Comment by jsilvestre** [comment]
Oh right! I was looking at days, not times. Thanks for the precision!

**Comment by poupotte** [comment]
This issue is now fixed.
