### ISSUE TITLE
Do not update event color after calendar change until the change is saved

### ISSUE THREAD

**Issue by nicofrand** [cozy/cozy-calendar#465]
**Steps to reproduce:**

0. Click on an event, change the agenda
0. Click on "Cancel"

This does not happen if I close the event's popup by pressign the <kbd>Esc</kbd> key.

**What happens:**

0. The color of the event is modified according to the agenda's color
0. When I refresh the page the event's color came back to its previous color : the event's agenda was not modified

**What I expect:**

Several solutions:

* Do not update the event's color until I click on "save" 
* When I click on "Cancel", reset the color to the previous color (actually the good one since the modification has been canceled)

**Comment by poupotte** [comment]
This issue is fixed on version 1.0.37 .
