### ISSUE TITLE
Hour of recurring events is wrong

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-calendar#466]
As reported [on the forum](https://forum.cozy.io/t/agenda-bugs/1564/13) : 
« Agenda (version calendar1.0.30) sur mon instance. Je crée une tâche répétée toutes les semaines. Dans le choix des horaires, à la création, je choisis 19:00. Ca me propose 12:00AM (problème d'horaire). Je corrige. Je valide. La tâche commence à 12:00.
Je corrige en définissant heure de début : 19:00. Heure de fin : 20:00. Les dates et heures au survol de la tâche sont bons. L'affichage fait commencer la tâche à 20:00.
Une tâche du même type non récurrente est correctement affichée.
Un redémarrage de l'appli ou de l'instance n'y change rien.
Sur l'appli Calendrier de FirefoxOS que je synchronise avec mon instance Cozy, les dates et heures sont correctement affichées et aux bonnes dates/heures.

=> Donc le bug est au niveau AFFICHAGE des tâches récurrentes dans Calendar. »

Probably related to #457

**Comment by jsilvestre** [comment]
It is a duplicate of #457 so I close this one.
