### ISSUE TITLE
Logo URL in public event pages is a 404

### ISSUE THREAD

**Issue by bnjbvr** [cozy/cozy-calendar#473]
Right here: https://github.com/cozy/cozy-calendar/blob/development/client/event_public_fr.jade#L14 and on the event_public_en.jade page as well.

Random hack suggestion: you can use the localization features to ensure there's no duplication of the URL in the code (by providing a key for this URL and the value only for the default locale).

**Comment by poupotte** [comment]
Thanks @bnjbvr for your report.

**Comment by poupotte** [comment]
It works well on development branch. Thanks @clochix .

**Comment by poupotte** [comment]
This issue is fixed in new version 1.0.31
