### ISSUE TITLE
FullCalendar locales are missing

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-calendar#475]
FullCalendar provide its own locale files, but it appears that:
 - we only have french and Portuguese (???) in our repo;
 - when a language is missing, FullCalendar uses the Portuguese locale.

Our Spanish translator is asking why his calendar is displayed in Portuguese ,-)

We use a pretty old version of this component, so we should be careful on which version of the locale files we add.

**Comment by clochix** [comment]
As a side note, this is a little bit hard to maintain, as we need the locale files for:
 - fullcalendar
 - moment
 - the datepicker (seems that latest versions of the datepicker use moment, so we could probably get rid of this locale files once the component has been updated)

**Comment by poupotte** [comment]
This issue is noew fixed in new release: v1.0.31. Thanks @clochix
