### ISSUE TITLE
Forbidden chars in events make the application silently fail

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-calendar#481]
Some events imported from Google contains characters not supported by JavaScript inside browsers (like OxFFFb). The browser fails to parse the string and the application silently stop loading.
We should probably cleanup the data at a deeper level, like in CozyDB or inside the data-system.

This problem affect a user who imported a calendar from Google Calendar.

**Comment by poupotte** [comment]
Thanks @clochix !
