### ISSUE TITLE
Total number of events to import is sometime wrong

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-calendar#488]
After a successful import of an ics file, I get 843/832 events imported.
Investigating…

**Comment by poupotte** [comment]
Thanks @clochix ! Do you have a scenario to reproduce this issue (to test it)  ?

**Comment by clochix** [comment]
This is related to #491: some events in an iCalendar file had the same UID. As we use this field as collection key, only the first one was added.
But this fix probably just masks an error: the display is fixed, but the server side behavior is probably wrong: we shouln't import this events twice. Will be fixed in #491

**Comment by poupotte** [comment]
Ok, thanks @clochix !
