### ISSUE TITLE
Read-only external ical calendar over http/https

### ISSUE THREAD

**Issue by arthurlutz** [cozy/cozy-calendar#493]
It would be nice to be able to use external calendars that are made available though https. (for example an unnamed  train reservation service publishes an ical file on a generated URL).

**Comment by frankrousseau** [comment]
We are working on a workaround through konnectors: https://github.com/cozy-labs/konnectors/pull/202

**Comment by frankrousseau** [comment]
It's integrated in the last version of Konnectors. Could you try it?
