### ISSUE TITLE
error 500 with jade.js

### ISSUE THREAD

**Issue by icefinger** [cozy/cozy-calendar#503]
Dear developpers,
I installed cozy cloud on a fresh debian 8.4 using the direction given on the cozy cloud site for debian (repository). It works well except for the calendar application. I go an error 500

`
Connect
500 Error: Failed to lookup view "index.jade" in views directory "./client"

    at EventEmitter.app.render (/usr/local/cozy/apps/calendar/node_modules/cozy-calendar/node_modules/americano/node_modules/express/lib/application.js:519:17)
    at ServerResponse.res.render (/usr/local/cozy/apps/calendar/node_modules/cozy-calendar/node_modules/americano/node_modules/express/lib/response.js:933:7)
    at /usr/local/cozy/apps/calendar/node_modules/cozy-calendar/build/server/controllers/index.js:68:16
    at /usr/local/cozy/apps/calendar/node_modules/cozy-calendar/node_modules/async/lib/async.js:718:13
    at /usr/local/cozy/apps/calendar/node_modules/cozy-calendar/node_modules/async/lib/async.js:46:16
    at done (/usr/local/cozy/apps/calendar/node_modules/cozy-calendar/node_modules/async/lib/async.js:236:21)
    at /usr/local/cozy/apps/calendar/node_modules/cozy-calendar/node_modules/async/lib/async.js:37:16
    at /usr/local/cozy/apps/calendar/node_modules/cozy-calendar/node_modules/async/lib/async.js:715:17
    at /usr/local/cozy/apps/calendar/node_modules/cozy-calendar/node_modules/cozydb/lib/model.js:213:18
    at /usr/local/cozy/apps/calendar/node_modules/cozy-calendar/node_modules/cozydb/lib/cozymodel.js:294:18

`

Thanks for your great job

**Comment by clochix** [comment]
Hi @icefinger,

Thanks for reporting!

Is this related to [this thread](https://forum.cozy.io/t/calendar-app-500-error/2266)? If so, the new version of Calendar, 1.0.35, available for a few hours now, could have fixed it.

**Comment by jsilvestre** [comment]
I am closing because it is most likely a solved issue. Let us know if something is still wrong for you @icefinger. Anyway, thanks for reporting.
Cheers!
