### ISSUE TITLE
Adding a new calendar is broken

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-calendar#515]
Reported by @ZeHiro.
Nothing happen when we click on the "+" icon to create a new calendar.

**Comment by clochix** [comment]
Probably related: calendars which have no event for current month are not displayed.

**Comment by frankrousseau** [comment]
Yep it's probably due to the fact we load only recent events.

**Comment by clochix** [comment]
A user confirms that creating an event in a calendar from its phone make the calendar display on the Web UI.

**Comment by poupotte** [comment]
New calendar version (1.0.37) solves this issue
