### ISSUE TITLE
Bring back the week view

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-calendar#528]
We receive reports from users who used a lot the week view and are sad it disappeared.

I hope we'll be able to fix it and activate it again some day.

**Comment by genma** [comment]
I used the week view each time. It's very useful and this how I organise myself : day by day, week per week. The list view don't show the "free time" ; in the month view, it's too small too...
Hope this feature will be back.

**Comment by genma** [comment]
I confirm I really miss week view. I need it :-)

**Comment by kosssi** [comment]
May be you can install old release meantime.

**Comment by clochix** [comment]
Another user is requesting a weekly view (contact email):
“Having a weekly view would be very nice in the calendar view. Seven rows for the seven days per week, with 24 rows each for the 24 hours per day. The height of one hour slot should also be configurable, such that you can visualize a whole week on your screen without the need to scroll. Similar to SOGo's[0] and Lightning's[1] weekly view:
[0] https://sogo.nu/typo3temp/pics/3622cf3a58.png
[1] https://addons.cdn.mozilla.net/user-media/previews/full/18/18246.png?src=api&modified=1331218902

The duration of an event would then be symbolized by that event's rectangle's height.

Right now, the monthly view is okay, but it doesn't give you a week's (or other time period's) time structure _at a glance_. This is because events only have their corresponding calendar (as color) and day (as table cell) visualized. Visualizing the events as proposed would also give the user user the benefit of a visualization of their free time (as blank space).

Most importantly, a weekly view would really help with planning ahead quickly, which is the whole point of a calendar. :)
”

**Comment by Zykino** [comment]
+1

**Comment by arnolddumas** [comment]
This feature would be really appreciated.

**Comment by clochix** [comment]
[One more vote](https://forum.cozy.io/t/calendar-improvements/3466).

**Comment by clochix** [comment]
By email: “clearly a calendar without a week view is not usable for me, it's almost the only view I use”

**Comment by clochix** [comment]
By email “Il n'y a pas de vue par semaine, ce qui rend l'outil moyennement utilisable en mode professionnel (avec de nombreux calendriers et évènements)”

**Comment by clochix** [comment]
Another user is requesting by email this view, and also a daily view.

**Comment by clochix** [comment]
One more https://forum.cozy.io/t/week-view-calendar/3882

**Comment by jabby** [comment]
👍 I agree.

**Comment by clochix** [comment]
[“avoir d'autres vues que mois ou liste comme semaine”](https://mesinfos.fing.org/forum/d/42-calendar-un-seul-calendrier-import/7)

**Comment by clochix** [comment]
By email: “Week view 99% of the time (…) The absence of week view is blocking for my use-case”

**Comment by clochix** [comment]
Thanks to @frankrousseau, [the week view is back, at last](https://github.com/cozy/cozy-calendar/pull/621)!!!
We have just released version 1.047 of the calendar application, give it a try!
