### ISSUE TITLE
Wrong end date of recurrent event

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-calendar#545]
This is what I observed : 
I create an event on tuesday (a few hours) on the webui
I want it to be recurrent (every week) but with an end date
I then select the end date in the modal (which is exactly 10 weeks after the first event, also a tuesday)
But the recurrent event does not end on the selected date (it ends the week before). I need to select the end date the day after the tuesday (a wednesday then).

**Comment by clochix** [comment]
Thanks for reporting @ZeHiro .

I know @gregorylegarec is working to fix issues with recurring events, pinging him.

**Comment by gregorylegarec** [comment]
Thanks for your feedback @ZeHiro, at this time we have a lot of issues with reccuring events, so the work have been a little bit delayed.
We will let you know when the issue is fixed.

**Comment by ZeHiro** [comment]
@gregorylegarec 
No worry, as long as I know the work around, I can wait.

**Comment by jsilvestre** [comment]
We created a mega-issue about recurring events. See https://github.com/cozy/cozy-calendar/issues/583.
