### ISSUE TITLE
Object has no method 'find'

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-calendar#572]
Reported [on the forum](https://forum.cozy.io/t/calendar-is-bugged-in-frontend/2870/9):

> My calendar version is also 1.0.40 and I have the message "server error" each time I try to create an event (recursive or not), even if the event is created when I reload the page.
> 
> My error message is also
> 
> Calendar server is listening on port 9113...
> info - realtime-adapter | socket.io initialized
> 
> /usr/local/cozy/apps/calendar/build/server/share/share_handler.js:10
>   hasGuestToShare = guests.find(function(guest) {
>                            ^
> TypeError: Object  has no method 'find'
>     at Object.module.exports.sendShareInvitations (/usr/local/cozy/apps/calendar/build/server/share/share_handler.js:10:28)
>     at /usr/local/cozy/apps/calendar/build/server/controllers/events.js:74:29
>     at /usr/local/cozy/apps/calendar/node_modules/cozydb/lib/model.js:84:18
>     at /usr/local/cozy/apps/calendar/node_modules/cozydb/lib/cozymodel.js:88:18
>     at parseBody (/usr/local/cozy/apps/calendar/node_modules/cozydb/node_modules/request-json-light/main.js:75:10)
>     at IncomingMessage.<anonymous> (/usr/local/cozy/apps/calendar/node_modules/cozydb/node_modules/request-json-light/main.js:109:14)
>     at IncomingMessage.emit (events.js:117:20)
>     at _stream_readable.js:929:16
>     at process._tickCallback (node.js:419:13)
> 

@gregorylegarec is this related to the new sharing features?

**Comment by poupotte** [comment]
This issue should be now fixed.
