### ISSUE TITLE
Error 14 with Calendar on Mac

### ISSUE THREAD

**Issue by pierrevdk** [cozy/cozy-calendar#582]
I tried to sync a Cozy Cloud calendar with the Calendar app on my Mac, but I have the following error: Une erreur imprévue est survenue sur la requête (domaine CalCalDAVErrorDomain / erreur 14).

**Comment by jsilvestre** [comment]
Closed in favor of https://github.com/cozy/cozy-sync/issues/136 because this is related to synchronization.
