### ISSUE TITLE
Deleting an instance of a recuring event deletes all the instances

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-calendar#597]
I would like to be able to delete an instance of a recurring event, but it deletes all the instances.
Also, the information of the a recuring event are the one of the original event, and not the one which the user clicked. Which is weired.

**Comment by jsilvestre** [comment]
Thank you for the report. It's a specific case of #238 so I let this opened for now so we are aware of this when we treat it.

**Comment by nicofrand** [comment]
For the original event displayed instead of the current event: https://github.com/cozy/cozy-calendar/issues/403

**Comment by ZeHiro** [comment]
@jsilvestre managing exceptions is what I want to do. so I think this is a duplicate of #238

**Comment by jsilvestre** [comment]
Ok, I close then! Thanks!
