### ISSUE TITLE
Error in timezone management

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-calendar#602]
I use this feed for "jours feriés" (with konnectors)
https://www.mozilla.org/media/caldata/FrenchHolidays.ics

Expected: 
Imported events should be diplayed for one full day

Observed: 
events are from (for toussaint) : 
- 1/11/16 at 1:00 am
- to 2/11/16 1:00 am

**Comment by Zykino** [comment]
Yep I saw this and also those weird comportment:
* The events are good looking in cozy web interface for Month (0:00 Toussaint)
* List are a bit more weird but at least in one event and not one for each day (01:00 - 01:00 Toussaint)
* Details for "Assomption" specifies: from 15/08/2010 2:00 am to 16/08/2010 2:00am recurring each years.
* So the details are not correct : **hours is not 0:00 -> 0:00**, year is 2010 (less important or expected)
* Synced on Android I see 2 events one for each days (in all views) which is much more annoying (Synced with Cozy Mobile, Calendar is [Etar](https://github.com/xsoh/Etar-Calendar))
* Time change is not taking into account (Assomption is from 2am to 2am while Toussaint is from 1am to 1am)

I have the events and they are looking OK on cozy but details are wrong and bad looking on external calendar.

**Comment by nicofrand** [comment]
Related: I don't get why the "AM" part appears whereas I'm using cozy in French and all other events are displayed on a 24h basis (ex: 23:00 and not 11:00 PM).

**Comment by clochix** [comment]
Thanks for reporting and commenting ☺

**Comment by jsilvestre** [comment]
Timezones are not well handled in Cozy, especially with recurring events :( Sorry about that!

I add this issue to the "main" issue about that problem and close this one if you don't mind.

Thank you again for reporting.
