### ISSUE TITLE
Several bugs in the display of a recurring event

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-calendar#607]
![datesmultiples](https://cloud.githubusercontent.com/assets/7999082/19269503/40bd964c-8fbb-11e6-9092-9461dc75350b.png)

On the image I see a lot of different bugs : 
- The start hour is different in 3 places (on the event, in the edit modal of the event and in the edit bubble for the hour.
- The edit bubble is not expected (not shown on other events) and it uses AM/PM displays whereas my cozy is in french. The bubble never hides once shown

Here is the information about the event : 
Start 2016-10-04T19:00:00.000
End 2016-10-04T22:00:00.000
rrule   FREQ=WEEKLY;WKST=MO;BYDAY=TU;UNTIL=20161220T000000Z 
Alarms 0 : {"trigg":"-PT1H","action":"DISPLAY"}
timezone: Europe/Paris

There could be an explanation for the hour in the modal : the previous date of the recurring event use to be 11 to 12.

**Comment by jsilvestre** [comment]
Thank you for reporting, I added it to the related [mega issue](https://github.com/cozy/cozy-calendar/issues/583). Closing here!
